config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, :defaults => { :format => 'json' } do
    devise_for :users, controllers: {
      registrations: 'api/users/registrations',
      sessions: 'api/users/sessions',
      passwords: 'api/users/passwords',
      confirmations: 'api/users/confirmations'
    }

    namespace :admins do
      resources :posts
    end

    namespace :users do
      resources :posts
      resources :profiles
    end
  end

  match "*path", to: "application#index", format: false, via: :get

  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  root 'application#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  namespace :users do
    resources :posts
  end

  namespace :admins do
    resources :posts
  end
  
end

app/controllers/api/users/profiles_controller.rb
class Api::Users::ProfilesController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= gravatar_for @user %>
    <h3><%= @user.name %></h3>
    <p><%= @user.email %></p>
    <% if current_user&.id == @user.id %>
      <%= link_to 'Settings', edit_user_registration_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="col-md-9">
    <%= will_paginate @posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
    <table class="table">
      <thead>
      <tr>
        <th>Title</th>
        <th>Created</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title.truncate(100), users_post_path(post) %></td>
          <td><%= time_ago_in_words(post.created_at) %> ago</td>
          <% if can? :edit, post %>
            <td><%= link_to 'Edit', edit_users_post_path(post) %></td>
          <% end %>
          <% if can? :destroy, post %>
            <td><%= link_to 'Destroy', users_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
  </div>
</div>